rust_binary(
    name = "demo",
    srcs = ["src/main.rs"],
    deps = [":demolib"],
)

rust_library(
    name = "demolib",
    srcs = ["src/lib.rs", "src/main.rs"],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "asd",
    srcs = ["BUCK"],
)
